shfmt

diff --git a/debmany b/debmany
--- a/debmany
+++ b/debmany
@@ -1,15 +1,19 @@
 #!/bin/bash
 trapcom_() {
-rm -f /tmp/.debmany.dblock
-echo -e "\e[1;31mInterrupt signal recieved"
-exit 8
+	rm -f /tmp/.debmany.dblock
+	echo -e "\e[1;31mInterrupt signal recieved"
+	exit 8
 }
-rm_db(){
-rm -f /tmp/.debmany.dblock
+rm_db() {
+	rm -f /tmp/.debmany.dblock
 }
-tch_db(){
-if [ -f "/tmp/.debmany.dblock" ]; then echo -e "debmany already running. Use \e[1;36mdebmany -rdblock\e[0m to force remove dblock file"; exit 9; else
-touch /tmp/.debmany.dblock; fi
+tch_db() {
+	if [ -f "/tmp/.debmany.dblock" ]; then
+		echo -e "debmany already running. Use \e[1;36mdebmany -rdblock\e[0m to force remove dblock file"
+		exit 9
+	else
+		touch /tmp/.debmany.dblock
+	fi
 }
 dirname=pkgmany-storage
 many_syncurl="https://github.com/BiteDasher/pkgmany-storage.git"
@@ -17,10 +21,11 @@ sync_path="/usr/share/debmany"
 build_path="$HOME/.cache/debmany"
 [ ! -d "$sync_path" ] && sudo mkdir /usr/share/debmany
 if ! [ -f "$sync_path/registry" ]; then
-echo -e "Looks like database folder not created. Create it with \e[1;32mdebmany -c\e[0m"; fi
+	echo -e "Looks like database folder not created. Create it with \e[1;32mdebmany -c\e[0m"
+fi
 case "$1" in
--h|--help|help|w)
-cat <<EOF
+-h | --help | help | w)
+	cat << EOF
 Usage: debmany [OPTION...] ...
 debmany: creates a .deb package based on the source code or just download it from the URL (frontend for pkgmany)
 Examples:
@@ -43,113 +48,253 @@ Examples:
 	-rdblock --remove-database-lock   (DO ONLY WHEN YOU KNOW WHY) Force remove of .dblock file
 	-h --help			  show this message
 EOF
-;;
--c|--update-db)
-[ $(id -u) -ne 0 ] && { echo "This script must be run as root" ; exit 1 ; }
-tch_db
-[ ! -f "$sync_path/registry" ] && touch $sync_path/registry
-if [ -d "$sync_path/$dirname" ]; then echo -e "Database cloned. \e[1;32mupdating\e[0m..."
-cd $sync_path/$dirname && git pull --rebase origin storage || { echo -e "\e[0;31mSomething went wrong...\e[0m" ; rm_db ; exit 4 ; } ; else
-cd $sync_path && git clone -b storage $many_syncurl || { echo -e "\e[0;31mSomething went wrong...\e[0m" ; rm_db ; exit 4 ; } ; fi
-echo -e "\e[1;32mSuccess!\e[0m"; rm_db
-;;
--cc|--clean-cache)
-[ ! -d "$sync_path/$dirname" ] && { echo -e "Database not cloned. Use \e[1;32mdebmany -c\e[0m to clone" ; exit 3 ; }
-rm -rf $build_path/*
-;;
--i|--install)
-[ ! -d "$sync_path/$dirname" ] && { echo -e "Database not cloned. Use \e[1;32mdebmany -c\e[0m to clone" ; rm_db ; exit 3 ; }
-[ ! "${__DEPS_INSTALL__}" ] && tch_db
-[ ! -d "$build_path" ] && mkdir -p  $build_path
-[ ! -f "$sync_path/$dirname/$2" ] && { echo -e "Package \e[1;33m$2\e[0m not exists" ; rm_db ; exit 5 ; }
-if [ -f "$build_path/$2/.sources_exists" ]; then
-echo -e "\e[0;33mSource files of this package already downloaded. Remove it [Y/n]?\e[0m"; read -rp "> " source_a; case "$source_a" in Y*|y*|"")
-rm -rf $build_path/$2
-cd $build_path; mkdir $2; cd $2 && cp $sync_path/$dirname/$2 ./DEBBUILD || { echo -e "\e[0;31mSomething went wrong...\e[0m" ; rm_db ; exit 4 ; };; *) cd $build_path/$2 ; esac; else
-[ -d "$build_path/$2" ] && rm -rf $build_path/$2; cd $build_path; mkdir $2; cd $2 && cp $sync_path/$dirname/$2 ./DEBBUILD || { echo -e "\e[0;31mSomething went wrong...\e[0m" ; rm_db ; exit 4 ; }; fi
-eval $(source DEBBUILD; [ "$manydeps" ] && echo "internal_deps=("${manydeps[@]}")";)
-if [ "$internal_deps" ]; then echo -e "\e[0;33mdebmany dependencies found:\e[0m ${internal_deps[@]}\nInstall them? [Y/n]"
-read -rp "> " manydeps_q
-case "$manydeps_q" in
-Y*|y*|"")
-export __DEPS_INSTALL__=1
-for pkg2 in ${internal_deps[@]}; do
-if [ "$(cat $sync_path/registry | grep -x $pkg2)" ]; then : ; else
-debmany -i $pkg2; fi; done; unset __DEPS_INTALL__ ;; *) : ;; esac; fi
-pkgmany
-sudo gdebi *.deb || { echo -e "\n\e[0;31mSomething went wrong...\e[0m" ; rm_db ; exit 4 ; }
-eval $(source DEBBUILD; echo debname="$debname"; echo _rev="$_rev";); if [ -n "${_rev}" ]; then packagename="${debname}-${_rev}"; else packagename="${debname}"; fi
-if ! [ "$(apt-cache pkgnames | grep -x $packagename)" ]; then
-echo -e "\n\e[0;31mSomething went wrong. Package not installed.\e[0m" ; rm_db ; exit 4; else
-if [ -z "$(cat $sync_path/registry | grep -x $packagename)" ]; then if [ -n "${_rev}" ]; then [ "$2" != "$packagename" ] && echo -e "\e[1m! ${2} installed as ${packagename}$clre"; fi; fi
-[ ! "$(cat $sync_path/registry | grep -x $packagename)" ] && echo $packagename | sudo tee -a $sync_path/registry &>/dev/null
-rm_db; fi
-;;
--ii|--addto-registry)
-[ ! -d "$sync_path/$dirname" ] && { echo -e "Database not cloned. Use \e[1;32mdebmany -c\e[0m to clone" ; rm_db ; exit 3 ; }
-[ $(id -u) -ne 0 ] && { echo "This option must be run as root" ; exit 1 ; }
-tch_db
-[ ! "$(cat $sync_path/registry | grep -x $2)" ] && echo $2 >> $sync_path/registry || { echo -e "Package \e[1;33m$2\e[0m exists" ; rm_db ; exit 6 ; }
-rm_db
-;;
--l|--list)
-[ ! -d "$sync_path/$dirname" ] && { echo -e "Database not cloned. Use \e[1;32mdebmany -c\e[0m to clone" ; exit 3 ; }
-ls $sync_path/$dirname | cat
-;;
--rl|--registry-list)
-[ ! -d "$sync_path/$dirname" ] && { echo -e "Database not cloned. Use \e[1;32mdebmany -c\e[0m to clone" ; exit 3 ; }
-cat $sync_path/registry
-;;
--r|--remove)
-[ $(id -u) -ne 0 ] && { echo "This option must be run as root" ; exit 1 ; }
-[ ! -d "$sync_path/$dirname" ] && { echo -e "Database not cloned. Use \e[1;32mdebmany -c\e[0m to clone" ; rm_db ; exit 3 ; }
-[ ! "$(apt-cache pkgnames | grep -x $2)" ] && { echo -e "Package \e[1;33m$2\e[0m not installed" ; exit 5 ; }
-tch_db
-apt purge $2 || { echo -e "\e[0;31mSomething went wrong...\e[0m" ; rm_db ; exit 4 ; }
-[ "$(cat $sync_path/registry | grep -x $2)" ] && sed "/$2/d" -i $sync_path/registry
-rm_db
-;;
--rr|--removefrom-registry)
-[ $(id -u) -ne 0 ] && { echo "This option must be run as root" ; exit 1 ; }
-[ ! -d "$sync_path/$dirname" ] && { echo -e "Database not cloned. Use \e[1;32mdebmany -c\e[0m to clone" ; exit 3 ; }
-tch_db
-[ "$(cat $sync_path/registry | grep -x $2)" ] && sed "/$2/d" -i $sync_path/registry || { echo -e "Package \e[1;33m$2\e[0m not found" ; rm_db ; exit 6 ; }
-rm_db
-;;
--rs|--remove-sources)
-[ ! -d "$sync_path/$dirname" ] && { echo -e "Database not cloned. Use \e[1;32mdebmany -c\e[0m to clone" ; exit 3 ; }
-rm -rf $build_path/*/.sources_exists
-rm -rf $build_path/*/*-source
-;;
--u|--update)
-[ $(id -u) -ne 0 ] && { echo "This option must be run as root" ; exit 1 ; }
-[ ! -d "$sync_path/$dirname" ] && { echo -e "Database not cloned. Use \e[1;32mdebmany -c\e[0m to clone" ; exit 3 ; }
-[ -z "$(cat $sync_path/registry)" ] && { echo "Nothing to check" ; exit 7 ; }
-tch_db
-rm -f /tmp/.debmany
-touch /tmp/.debmany
-for pkg in $(cat $sync_path/registry); do
-eval $(source $sync_path/$dirname/$pkg; [ ! "$debrel" ] && debrel=1; echo version1="$debver-$debrel";)
-version2="$(apt-cache show $pkg | grep -E "Version:" | head -n 1 | cut -c10-100)"
-if [ "$version1" != "$version2" ]; then
-echo "$pkg $version2 --> $version1" > /tmp/.debmany
-fi; done
-if [ -z "$(cat /tmp/.debmany)" ]; then echo "Nothing to update."; rm_db; else
-cat /tmp/.debmany; fi; rm_db
-;;
--redb|--recreate-database)
-[ $(id -u) -ne 0 ] && { echo "This option must be run as root" ; exit 1 ; }
-trap true SIGINT
-trap true SIGTERM
-mv -f $sync_path/registry /tmp/.registry
-rm -rf $sync_path/* $sync_path/.git
-cd $sync_path && git clone -b storage $many_syncurl || { echo -e "\e[0;31mSomething went wrong...\e[0m" ; exit 4 ; }
-mv -f /tmp/.registry $sync_path/registry; chmod 777 $sync_path/registry; echo -e "\e[1;32mSuccess!\e[0m"
-;;
--rdblock|--remove-database-lock)
-rm_db
-;;
+	;;
+-c | --update-db)
+	[ $(id -u) -ne 0 ] && {
+		echo "This script must be run as root"
+		exit 1
+	}
+	tch_db
+	[ ! -f "$sync_path/registry" ] && touch $sync_path/registry
+	if [ -d "$sync_path/$dirname" ]; then
+		echo -e "Database cloned. \e[1;32mupdating\e[0m..."
+		cd $sync_path/$dirname && git pull --rebase origin storage || {
+			echo -e "\e[0;31mSomething went wrong...\e[0m"
+			rm_db
+			exit 4
+		}
+	else
+		cd $sync_path && git clone -b storage $many_syncurl || {
+			echo -e "\e[0;31mSomething went wrong...\e[0m"
+			rm_db
+			exit 4
+		}
+	fi
+	echo -e "\e[1;32mSuccess!\e[0m"
+	rm_db
+	;;
+-cc | --clean-cache)
+	[ ! -d "$sync_path/$dirname" ] && {
+		echo -e "Database not cloned. Use \e[1;32mdebmany -c\e[0m to clone"
+		exit 3
+	}
+	rm -rf $build_path/*
+	;;
+-i | --install)
+	[ ! -d "$sync_path/$dirname" ] && {
+		echo -e "Database not cloned. Use \e[1;32mdebmany -c\e[0m to clone"
+		rm_db
+		exit 3
+	}
+	[ ! "${__DEPS_INSTALL__}" ] && tch_db
+	[ ! -d "$build_path" ] && mkdir -p $build_path
+	[ ! -f "$sync_path/$dirname/$2" ] && {
+		echo -e "Package \e[1;33m$2\e[0m not exists"
+		rm_db
+		exit 5
+	}
+	if [ -f "$build_path/$2/.sources_exists" ]; then
+		echo -e "\e[0;33mSource files of this package already downloaded. Remove it [Y/n]?\e[0m"
+		read -rp "> " source_a
+		case "$source_a" in Y* | y* | "")
+			rm -rf $build_path/$2
+			cd $build_path
+			mkdir $2
+			cd $2 && cp $sync_path/$dirname/$2 ./DEBBUILD || {
+				echo -e "\e[0;31mSomething went wrong...\e[0m"
+				rm_db
+				exit 4
+			}
+			;;
+		*) cd $build_path/$2 ;; esac
+	else
+		[ -d "$build_path/$2" ] && rm -rf $build_path/$2
+		cd $build_path
+		mkdir $2
+		cd $2 && cp $sync_path/$dirname/$2 ./DEBBUILD || {
+			echo -e "\e[0;31mSomething went wrong...\e[0m"
+			rm_db
+			exit 4
+		}
+	fi
+	eval $(
+		source DEBBUILD
+		[ "$manydeps" ] && echo "internal_deps=("${manydeps[@]}")"
+	)
+	if [ "$internal_deps" ]; then
+		echo -e "\e[0;33mdebmany dependencies found:\e[0m ${internal_deps[@]}\nInstall them? [Y/n]"
+		read -rp "> " manydeps_q
+		case "$manydeps_q" in
+		Y* | y* | "")
+			export __DEPS_INSTALL__=1
+			for pkg2 in ${internal_deps[@]}; do
+				if [ "$(cat $sync_path/registry | grep -x $pkg2)" ]; then :; else
+					debmany -i $pkg2
+				fi
+			done
+			unset __DEPS_INTALL__
+			;;
+		*) : ;; esac
+	fi
+	pkgmany
+	sudo gdebi *.deb || {
+		echo -e "\n\e[0;31mSomething went wrong...\e[0m"
+		rm_db
+		exit 4
+	}
+	eval $(
+		source DEBBUILD
+		echo debname="$debname"
+		echo _rev="$_rev"
+	)
+	if [ -n "${_rev}" ]; then packagename="${debname}-${_rev}"; else packagename="${debname}"; fi
+	if ! [ "$(apt-cache pkgnames | grep -x $packagename)" ]; then
+		echo -e "\n\e[0;31mSomething went wrong. Package not installed.\e[0m"
+		rm_db
+		exit 4
+	else
+		if [ -z "$(cat $sync_path/registry | grep -x $packagename)" ]; then if [ -n "${_rev}" ]; then [ "$2" != "$packagename" ] && echo -e "\e[1m! ${2} installed as ${packagename}$clre"; fi; fi
+		[ ! "$(cat $sync_path/registry | grep -x $packagename)" ] && echo $packagename | sudo tee -a $sync_path/registry &> /dev/null
+		rm_db
+	fi
+	;;
+-ii | --addto-registry)
+	[ ! -d "$sync_path/$dirname" ] && {
+		echo -e "Database not cloned. Use \e[1;32mdebmany -c\e[0m to clone"
+		rm_db
+		exit 3
+	}
+	[ $(id -u) -ne 0 ] && {
+		echo "This option must be run as root"
+		exit 1
+	}
+	tch_db
+	[ ! "$(cat $sync_path/registry | grep -x $2)" ] && echo $2 >> $sync_path/registry || {
+		echo -e "Package \e[1;33m$2\e[0m exists"
+		rm_db
+		exit 6
+	}
+	rm_db
+	;;
+-l | --list)
+	[ ! -d "$sync_path/$dirname" ] && {
+		echo -e "Database not cloned. Use \e[1;32mdebmany -c\e[0m to clone"
+		exit 3
+	}
+	ls $sync_path/$dirname | cat
+	;;
+-rl | --registry-list)
+	[ ! -d "$sync_path/$dirname" ] && {
+		echo -e "Database not cloned. Use \e[1;32mdebmany -c\e[0m to clone"
+		exit 3
+	}
+	cat $sync_path/registry
+	;;
+-r | --remove)
+	[ $(id -u) -ne 0 ] && {
+		echo "This option must be run as root"
+		exit 1
+	}
+	[ ! -d "$sync_path/$dirname" ] && {
+		echo -e "Database not cloned. Use \e[1;32mdebmany -c\e[0m to clone"
+		rm_db
+		exit 3
+	}
+	[ ! "$(apt-cache pkgnames | grep -x $2)" ] && {
+		echo -e "Package \e[1;33m$2\e[0m not installed"
+		exit 5
+	}
+	tch_db
+	apt purge $2 || {
+		echo -e "\e[0;31mSomething went wrong...\e[0m"
+		rm_db
+		exit 4
+	}
+	[ "$(cat $sync_path/registry | grep -x $2)" ] && sed "/$2/d" -i $sync_path/registry
+	rm_db
+	;;
+-rr | --removefrom-registry)
+	[ $(id -u) -ne 0 ] && {
+		echo "This option must be run as root"
+		exit 1
+	}
+	[ ! -d "$sync_path/$dirname" ] && {
+		echo -e "Database not cloned. Use \e[1;32mdebmany -c\e[0m to clone"
+		exit 3
+	}
+	tch_db
+	[ "$(cat $sync_path/registry | grep -x $2)" ] && sed "/$2/d" -i $sync_path/registry || {
+		echo -e "Package \e[1;33m$2\e[0m not found"
+		rm_db
+		exit 6
+	}
+	rm_db
+	;;
+-rs | --remove-sources)
+	[ ! -d "$sync_path/$dirname" ] && {
+		echo -e "Database not cloned. Use \e[1;32mdebmany -c\e[0m to clone"
+		exit 3
+	}
+	rm -rf $build_path/*/.sources_exists
+	rm -rf $build_path/*/*-source
+	;;
+-u | --update)
+	[ $(id -u) -ne 0 ] && {
+		echo "This option must be run as root"
+		exit 1
+	}
+	[ ! -d "$sync_path/$dirname" ] && {
+		echo -e "Database not cloned. Use \e[1;32mdebmany -c\e[0m to clone"
+		exit 3
+	}
+	[ -z "$(cat $sync_path/registry)" ] && {
+		echo "Nothing to check"
+		exit 7
+	}
+	tch_db
+	rm -f /tmp/.debmany
+	touch /tmp/.debmany
+	for pkg in $(cat $sync_path/registry); do
+		eval $(
+			source $sync_path/$dirname/$pkg
+			[ ! "$debrel" ] && debrel=1
+			echo version1="$debver-$debrel"
+		)
+		version2="$(apt-cache show $pkg | grep -E "Version:" | head -n 1 | cut -c10-100)"
+		if [ "$version1" != "$version2" ]; then
+			echo "$pkg $version2 --> $version1" > /tmp/.debmany
+		fi
+	done
+	if [ -z "$(cat /tmp/.debmany)" ]; then
+		echo "Nothing to update."
+		rm_db
+	else
+		cat /tmp/.debmany
+	fi
+	rm_db
+	;;
+-redb | --recreate-database)
+	[ $(id -u) -ne 0 ] && {
+		echo "This option must be run as root"
+		exit 1
+	}
+	trap true SIGINT
+	trap true SIGTERM
+	mv -f $sync_path/registry /tmp/.registry
+	rm -rf $sync_path/* $sync_path/.git
+	cd $sync_path && git clone -b storage $many_syncurl || {
+		echo -e "\e[0;31mSomething went wrong...\e[0m"
+		exit 4
+	}
+	mv -f /tmp/.registry $sync_path/registry
+	chmod 777 $sync_path/registry
+	echo -e "\e[1;32mSuccess!\e[0m"
+	;;
+-rdblock | --remove-database-lock)
+	rm_db
+	;;
 *)
-echo "Unknown argument. Try debmany -h for help"; exit 2
-;;
+	echo "Unknown argument. Try debmany -h for help"
+	exit 2
+	;;
 esac
diff --git a/pkgmany b/pkgmany
--- a/pkgmany
+++ b/pkgmany
@@ -1,53 +1,64 @@
 #!/bin/bash
 purge_makedepends() {
-if [ -f ${curdir}/.makedeps ]; then
-printf "\n\e[1;33mRemove build dependencies?(They are not needed after building the package.)\e[0m [Y/n]"
-read -rp "> " mdquest
-case $mdquest in
-Y*|y*|"")
-sudo apt purge $(cat .makedeps | tr "\n" " ")
-rm .makedeps
-;;
-*)
-:
-;; esac; fi
+	if [ -f ${curdir}/.makedeps ]; then
+		printf "\n\e[1;33mRemove build dependencies?(They are not needed after building the package.)\e[0m [Y/n]"
+		read -rp "> " mdquest
+		case $mdquest in
+		Y* | y* | "")
+			sudo apt purge $(cat .makedeps | tr "\n" " ")
+			rm .makedeps
+			;;
+		*)
+			:
+			;;
+		esac
+	fi
 }
 checkaddfiles() {
-if [ "$(declare -f addfiles &>/dev/null; echo $?)" == 0 ]; then
-printf "\n\e[1;33mcreating additional files...$clre"
-addfiles; fi
+	if [ "$(
+		declare -f addfiles &> /dev/null
+		echo $?
+	)" == 0 ]; then
+		printf "\n\e[1;33mcreating additional files...$clre"
+		addfiles
+	fi
 }
 unpack() {
-  tar -xf $srcdir/* -C $srcdir/
+	tar -xf $srcdir/* -C $srcdir/
 }
 create_deb() {
-printf "\n\e[1;32mCreating .deb package...$clre"
-cd $pkgdir
-mkdir DEBIAN
-cd DEBIAN
-if [ "$(declare -f newver &>/dev/null; echo $?)" == 0 ]; then
-debver="$(newver)"; fi
-if [ "${_rev}" ]; then debname="${debname}-${_rev}"; fi
-echo "Package: $debname" >> control
-echo "Version: $debver-$debrel" >> control
-echo "Architecture: $debarch" >> control
-[ "$debpri" ] && echo "Priority: $debpri" >> control
-[ "$debsec" ] && echo "Section: $debsec" >> control
-[ "$debrec" ] && echo "Reccomends: $debrec" >> control
-[ "$debsug" ] && echo "Suggests: $debsug" >> control
-[ "$debcon" ] && echo "Conflicts: $debcon" >> control
-[ "$debbrk" ] && echo "Breaks: $debbrk" >> control
-[ "$debprv" ] && echo "Provides: $debprv" >> control
-[ "$debrep" ] && echo "Replaces: $debrep" >> control
-echo "Depends: $debdeps" >> control
-echo "Homepage: $url" >> control
-echo "Maintainer: $maintainer" >> control
-echo "Description: $debdesc" >> control
-[ "$debpostinst" ] && echo "$debpostinst" > postinst
-[ "$debprerm" ] && echo "$debprerm" > prerm
-[ "$debconffiles" ] && echo "$debconffiles" > conffiles
-cd .. && find . -type f ! -regex '.*.hg.*' ! -regex '.*?debian-binary.*' ! -regex '.*?DEBIAN.*' -printf '%P ' | xargs md5sum > DEBIAN/md5sums; cd DEBIAN
-cat <<EOF > copyright
+	printf "\n\e[1;32mCreating .deb package...$clre"
+	cd $pkgdir
+	mkdir DEBIAN
+	cd DEBIAN
+	if [ "$(
+		declare -f newver &> /dev/null
+		echo $?
+	)" == 0 ]; then
+		debver="$(newver)"
+	fi
+	if [ "${_rev}" ]; then debname="${debname}-${_rev}"; fi
+	echo "Package: $debname" >> control
+	echo "Version: $debver-$debrel" >> control
+	echo "Architecture: $debarch" >> control
+	[ "$debpri" ] && echo "Priority: $debpri" >> control
+	[ "$debsec" ] && echo "Section: $debsec" >> control
+	[ "$debrec" ] && echo "Reccomends: $debrec" >> control
+	[ "$debsug" ] && echo "Suggests: $debsug" >> control
+	[ "$debcon" ] && echo "Conflicts: $debcon" >> control
+	[ "$debbrk" ] && echo "Breaks: $debbrk" >> control
+	[ "$debprv" ] && echo "Provides: $debprv" >> control
+	[ "$debrep" ] && echo "Replaces: $debrep" >> control
+	echo "Depends: $debdeps" >> control
+	echo "Homepage: $url" >> control
+	echo "Maintainer: $maintainer" >> control
+	echo "Description: $debdesc" >> control
+	[ "$debpostinst" ] && echo "$debpostinst" > postinst
+	[ "$debprerm" ] && echo "$debprerm" > prerm
+	[ "$debconffiles" ] && echo "$debconffiles" > conffiles
+	cd .. && find . -type f ! -regex '.*.hg.*' ! -regex '.*?debian-binary.*' ! -regex '.*?DEBIAN.*' -printf '%P ' | xargs md5sum > DEBIAN/md5sums
+	cd DEBIAN
+	cat << EOF > copyright
 Format: https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/
 Upstream-Name: $debname
 Upstream-Contact: $author
@@ -57,24 +68,33 @@ Files: *
 Copyright: $year $author
 License: "${license}"
 EOF
-printf "  \e[0;32mok"
-printf "\n\e[1;33mBuilding \e[0;36m$debname$clre \e[1;33mpackage using dpkg-deb...$clre"
-cd $curdir
-dpkg-deb -b "$pkgdir" "$debname".deb; checkerror; printf "\n"
+	printf "  \e[0;32mok"
+	printf "\n\e[1;33mBuilding \e[0;36m$debname$clre \e[1;33mpackage using dpkg-deb...$clre"
+	cd $curdir
+	dpkg-deb -b "$pkgdir" "$debname".deb
+	checkerror
+	printf "\n"
 }
 checkerror() {
-if [ "$?" != 0 ]; then printf " \e[1;31merror$clre"; exit 1; else
-printf " \e[0;32mok\e[0m"; fi
+	if [ "$?" != 0 ]; then
+		printf " \e[1;31merror$clre"
+		exit 1
+	else
+		printf " \e[0;32mok\e[0m"
+	fi
 }
 clre="\e[0m"
 trapcom() {
-echo -e "\033[1;31mInterrupt signal recieved."; exit 5
+	echo -e "\033[1;31mInterrupt signal recieved."
+	exit 5
 }
 trap trapcom SIGTERM
 trap trapcom SIGINT
-if [ "$1" ]; then pkgmanyone=1; case $1 in
--h|--help|help|w)
-cat <<EOF
+if [ "$1" ]; then
+	pkgmanyone=1
+	case $1 in
+	-h | --help | help | w)
+		cat << EOF
 Usage: pkgmany [OPTION...] ...
 pkgmany: creates a .deb package based on the source code or just download it from the URL
 Examples:
@@ -89,97 +109,194 @@ Examples:
 	-c  --create		only create .deb package
 	-a  --all		create .deb package and install it
 EOF
-;;
--po|--package-only)
-[ ! -f DEBBUILD ] && { printf "\n\e[0;31mDEBBUILD not found.\e[0m Aborting...\n$clre" ; exit 1 ; }
-source DEBBUILD
-curdir="$(pwd)"
-pkgdir="$(pwd)/${debname}"
-[ ! -d "$pkgdir" ] && { printf "\n\e[0;36m\$pkgdir\e[1;32m not found$clre" ; exit 1 ; }
-srcdir="$(pwd)/${debname}-source"
-[ ! -d "$srcdir" ] && { printf "\n\e[0;36m\$srcdir\e[1;32m not found$clre" ; exit 1 ; }
-checkaddfiles; checkerror; package; checkerror
-;;
--u|--unpack)
-[ ! -f DEBBUILD ] && { printf "\n\e[0;31mDEBBUILD not found.\e[0m Aborting...\n$clre" ; exit 1 ; }
-source DEBBUILD
-curdir="$(pwd)"
-pkgdir="$(pwd)/${debname}"
-[ ! -d "$pkgdir" ] && { printf "\n\e[0;36m\$pkgdir\e[1;32m not found$clre" ; exit 1 ; }
-srcdir="$(pwd)/${debname}-source"
-[ ! -d "$srcdir" ] && { printf "\n\e[0;36m\$srcdir\e[1;32m not found$clre" ; exit 1 ; }
-unpack; checkerror
-;;
--c|--create)
-[ ! -f DEBBUILD ] && { printf "\n\e[0;31mDEBBUILD not found.\e[0m Aborting...\n$clre" ; exit 1 ; }
-source DEBBUILD
-curdir="$(pwd)"
-pkgdir="$(pwd)/${debname}"
-[ ! -d "$pkgdir" ] && { printf "\n\e[0;36m\$pkgdir\e[1;32m not found$clre" ; exit 1 ; }
-srcdir="$(pwd)/${debname}-source"
-[ ! -d "$srcdir" ] && { printf "\n\e[0;36m\$srcdir\e[1;32m not found$clre" ; exit 1 ; }
-rm -rf $pkgdir/*
-create_deb
-purge_makedepends
-;;
--a|--all)
-unset pkgmanyone
-;; esac; fi
+		;;
+	-po | --package-only)
+		[ ! -f DEBBUILD ] && {
+			printf "\n\e[0;31mDEBBUILD not found.\e[0m Aborting...\n$clre"
+			exit 1
+		}
+		source DEBBUILD
+		curdir="$(pwd)"
+		pkgdir="$(pwd)/${debname}"
+		[ ! -d "$pkgdir" ] && {
+			printf "\n\e[0;36m\$pkgdir\e[1;32m not found$clre"
+			exit 1
+		}
+		srcdir="$(pwd)/${debname}-source"
+		[ ! -d "$srcdir" ] && {
+			printf "\n\e[0;36m\$srcdir\e[1;32m not found$clre"
+			exit 1
+		}
+		checkaddfiles
+		checkerror
+		package
+		checkerror
+		;;
+	-u | --unpack)
+		[ ! -f DEBBUILD ] && {
+			printf "\n\e[0;31mDEBBUILD not found.\e[0m Aborting...\n$clre"
+			exit 1
+		}
+		source DEBBUILD
+		curdir="$(pwd)"
+		pkgdir="$(pwd)/${debname}"
+		[ ! -d "$pkgdir" ] && {
+			printf "\n\e[0;36m\$pkgdir\e[1;32m not found$clre"
+			exit 1
+		}
+		srcdir="$(pwd)/${debname}-source"
+		[ ! -d "$srcdir" ] && {
+			printf "\n\e[0;36m\$srcdir\e[1;32m not found$clre"
+			exit 1
+		}
+		unpack
+		checkerror
+		;;
+	-c | --create)
+		[ ! -f DEBBUILD ] && {
+			printf "\n\e[0;31mDEBBUILD not found.\e[0m Aborting...\n$clre"
+			exit 1
+		}
+		source DEBBUILD
+		curdir="$(pwd)"
+		pkgdir="$(pwd)/${debname}"
+		[ ! -d "$pkgdir" ] && {
+			printf "\n\e[0;36m\$pkgdir\e[1;32m not found$clre"
+			exit 1
+		}
+		srcdir="$(pwd)/${debname}-source"
+		[ ! -d "$srcdir" ] && {
+			printf "\n\e[0;36m\$srcdir\e[1;32m not found$clre"
+			exit 1
+		}
+		rm -rf $pkgdir/*
+		create_deb
+		purge_makedepends
+		;;
+	-a | --all)
+		unset pkgmanyone
+		;;
+	esac
+fi
 [ "$pkgmanyone" ] && exit 0
 pkgmanyver=1.0
 echo -e "Starting pkgmany \e[0;36m$pkgmanyver$clre"
-[ ! -f DEBBUILD ] && { printf "\n\e[0;31mDEBBUILD not found.\e[0m Aborting...\n$clre" ; exit 1 ; }
+[ ! -f DEBBUILD ] && {
+	printf "\n\e[0;31mDEBBUILD not found.\e[0m Aborting...\n$clre"
+	exit 1
+}
 source DEBBUILD
 curdir="$(pwd)"
 pkgdir="$(pwd)/${debname}"
-if [ -d "$pkgdir" ]; then printf "\n\e[1;32mRemoving $clre${pkgdir}\e[1;32m...$clre"; rm -rf $pkgdir
-checkerror; fi
+if [ -d "$pkgdir" ]; then
+	printf "\n\e[1;32mRemoving $clre${pkgdir}\e[1;32m...$clre"
+	rm -rf $pkgdir
+	checkerror
+fi
 mkdir $pkgdir
 srcdir="$(pwd)/${debname}-source"
 if [ -f "$(pwd)/.sources_exists" ]; then
-printf "\n\e[1;32mSources downloaded. \e[1;34mContinue...$clre"; else
-if [ -d "$srcdir" ]; then printf "\n\e[1;32mRemoving $clre${srcdir}\e[1;32m...$clre"; rm -rf $srcdir
-checkerror; fi
-mkdir $srcdir; fi
-[ -f *.deb ] && { printf "\n\e[1;32mMoving .deb in .backup$clre" ; [ -d .backup ] && rm -rf .backup; mkdir .backup ; mv *.deb .backup/ ; checkerror ; }
+	printf "\n\e[1;32mSources downloaded. \e[1;34mContinue...$clre"
+else
+	if [ -d "$srcdir" ]; then
+		printf "\n\e[1;32mRemoving $clre${srcdir}\e[1;32m...$clre"
+		rm -rf $srcdir
+		checkerror
+	fi
+	mkdir $srcdir
+fi
+[ -f *.deb ] && {
+	printf "\n\e[1;32mMoving .deb in .backup$clre"
+	[ -d .backup ] && rm -rf .backup
+	mkdir .backup
+	mv *.deb .backup/
+	checkerror
+}
 ###
 if [ "$makedepends" ]; then
-printf "\n\e[1;32mFound \e[0;36m\$makedepends\e[1;32m. Checking...$clre\n"
-dependerrARRAY=()
-rm -f .makedeps
-for pkg in ${makedepends[@]}; do
-if ! [ "$(apt-cache pkgnames | grep -x ${pkg})" ]; then
-printf "\n$clre$pkg\e[1;31m not found$clre"; dependerrARRAY+=(${pkg})
-else 
-[ ! "$(apt-mark showmanual | grep -x $pkg)" ] && echo $pkg >> .makedeps ; fi; done; fi
-if [ "$dependerrARRAY" ]; then echo -e " \e[1;31m\nerror$clre \e[0;31mFollowing dependencies not found at repositories:$clre ${dependerrARRAY[@]}"; rm .makedeps; exit 2; else [ -f .makedeps ] && { sudo apt install $(cat .makedeps | tr "\n" " ") ; printf " \e[0;32mok$clre" ; }; fi
+	printf "\n\e[1;32mFound \e[0;36m\$makedepends\e[1;32m. Checking...$clre\n"
+	dependerrARRAY=()
+	rm -f .makedeps
+	for pkg in ${makedepends[@]}; do
+		if ! [ "$(apt-cache pkgnames | grep -x ${pkg})" ]; then
+			printf "\n$clre$pkg\e[1;31m not found$clre"
+			dependerrARRAY+=(${pkg})
+		else
+			[ ! "$(apt-mark showmanual | grep -x $pkg)" ] && echo $pkg >> .makedeps
+		fi
+	done
+fi
+if [ "$dependerrARRAY" ]; then
+	echo -e " \e[1;31m\nerror$clre \e[0;31mFollowing dependencies not found at repositories:$clre ${dependerrARRAY[@]}"
+	rm .makedeps
+	exit 2
+else [ -f .makedeps ] && {
+	sudo apt install $(cat .makedeps | tr "\n" " ")
+	printf " \e[0;32mok$clre"
+}; fi
 if ! [ -f "$(pwd)/.sources_exists" ]; then
-printf "\n\e[1;32mDownloading sources...$clre\n"
-for source_get in ${sources[@]}; do
-	source_get_mtd="$(echo $source_get | cut -d":" -f1)"
-	case "${source_get_mtd}" in
-	wget) wget -O $srcdir/$(echo $source_get | cut -d":" -f2) $(echo $source_get | cut -d":" -f3-) -q --show-progress; checkerror ;;
-	curl) cd $srcdir && curl -L -o $(echo $source_get | cut -d":" -f2) --progress-bar $(echo $source_get | cut -d":" -f3-); checkerror ;;
-	git) echo; cd $srcdir && git clone $(echo $source_get | cut -d":" -f3-) $(echo $source_get | cut -d":" -f2) 1>/dev/null; checkerror ;;
-	esac; done
-if [ "$sha256sums" ]; then printf "\n\e[1;32mChecking sha256sums...$clre"; fi
-for ssum in ${!sha256sums[*]}; do
-	if [ "${sha256sums[$ssum]}" == SKIP ]; then
-	printf "\n\e[1;32mchecking$clre $(echo ${sources[$ssum]} | cut -d":" -f2)... \e[1;33mskip$clre"; else
-	printf "\n\e[1;32mchecking$clre $(echo ${sources[$ssum]} | cut -d":" -f2)..."
-	if [ "$(sha256sum $srcdir/$(echo ${sources[$ssum]} | cut -d":" -f2) | cut -d" " -f1)" != ${sha256sums[$ssum]} ]; then printf "\e[1;31m error$clre\n"; exit 1; else printf "\e[0;32m ok$clre"; fi; fi; done; fi
+	printf "\n\e[1;32mDownloading sources...$clre\n"
+	for source_get in ${sources[@]}; do
+		source_get_mtd="$(echo $source_get | cut -d":" -f1)"
+		case "${source_get_mtd}" in
+		wget)
+			wget -O $srcdir/$(echo $source_get | cut -d":" -f2) $(echo $source_get | cut -d":" -f3-) -q --show-progress
+			checkerror
+			;;
+		curl)
+			cd $srcdir && curl -L -o $(echo $source_get | cut -d":" -f2) --progress-bar $(echo $source_get | cut -d":" -f3-)
+			checkerror
+			;;
+		git)
+			echo
+			cd $srcdir && git clone $(echo $source_get | cut -d":" -f3-) $(echo $source_get | cut -d":" -f2) 1> /dev/null
+			checkerror
+			;;
+		esac
+	done
+	if [ "$sha256sums" ]; then printf "\n\e[1;32mChecking sha256sums...$clre"; fi
+	for ssum in ${!sha256sums[*]}; do
+		if [ "${sha256sums[$ssum]}" == SKIP ]; then
+			printf "\n\e[1;32mchecking$clre $(echo ${sources[$ssum]} | cut -d":" -f2)... \e[1;33mskip$clre"
+		else
+			printf "\n\e[1;32mchecking$clre $(echo ${sources[$ssum]} | cut -d":" -f2)..."
+			if [ "$(sha256sum $srcdir/$(echo ${sources[$ssum]} | cut -d":" -f2) | cut -d" " -f1)" != ${sha256sums[$ssum]} ]; then
+				printf "\e[1;31m error$clre\n"
+				exit 1
+			else printf "\e[0;32m ok$clre"; fi
+		fi
+	done
+fi
 if [ "$debpkg" ]; then
-printf "\n\e[1;36mMoving ${clre}.deb$clre \e[1;36mpackage...$clre"
-mv $srcdir/* $curdir/; checkerror; exit 0; fi
+	printf "\n\e[1;36mMoving ${clre}.deb$clre \e[1;36mpackage...$clre"
+	mv $srcdir/* $curdir/
+	checkerror
+	exit 0
+fi
 if ! [ -f "$curdir/.sources_exists" ]; then
-printf "\n\e[1;32mUnpacking sources..$clre."
-unpack; checkerror; fi
+	printf "\n\e[1;32mUnpacking sources..$clre."
+	unpack
+	checkerror
+fi
 printf "\n\e[1;32mBuilding...$clre"
 #if [ -f "$curdir/.sources_exists" ]; then [ -n "$(ls $curdir -I DEBBUILD -I ${debname} -I ${debname}-source)" ] && rm $(ls $curdir -I DEBBUILD -I ${debname}-source -I ${debname}); checkaddfiles; checkerror; else checkaddfiles; checkerror; fi
 cd $curdir
-if ! [ -f "$curdir/.sources_exists" ]; then checkaddfiles; checkerror; fi
+if ! [ -f "$curdir/.sources_exists" ]; then
+	checkaddfiles
+	checkerror
+fi
 touch $curdir/.sources_exists
-package; if [ "$?" != 0 ]; then printf " \e[1;31merror$clre"; purge_makedepends; exit 1; fi
-create_deb; if [ "$?" != 0 ]; then printf " \e[1;31merror$clre"; purge_makedepends; exit 1; fi
+package
+if [ "$?" != 0 ]; then
+	printf " \e[1;31merror$clre"
+	purge_makedepends
+	exit 1
+fi
+create_deb
+if [ "$?" != 0 ]; then
+	printf " \e[1;31merror$clre"
+	purge_makedepends
+	exit 1
+fi
 purge_makedepends
 rm $curdir/.sources_exists
