Fixes

diff --git a/pkgmany b/pkgmany
--- a/pkgmany
+++ b/pkgmany
@@ -1,6 +1,6 @@
 #!/bin/bash
 purge_makedepends() {
-if [ "$makedepends" ]; then
+if [ -f .makedeps ]; then
 printf "\n\e[1;33mRemove build dependencies?(They are not needed after building the package.)\e[0m [Y/n]"
 read -rp "> " mdquest
 case $mdquest in
@@ -142,7 +142,7 @@ if ! [ "$(apt-cache pkgnames | grep -x ${pkg})" ]; then
 printf "\n$clre$pkg\e[1;31m not found$clre"; dependerrARRAY+=(${pkg})
 else 
 [ ! "$(apt-mark showmanual | grep -x $pkg)" ] && echo $pkg >> .makedeps ; fi; done; fi
-if [ "$dependerrARRAY" ]; then echo -e " \e[1;31m\nerror$clre \e[0;31mFollowing dependencies not found at repositories:$clre ${dependerrARRAY[@]}"; rm .makedeps; exit 2; else [ "$makedepends" ] && { sudo apt install $(cat .makedeps | tr "\n" " ") ; printf " \e[0;32mok$clre" ; }; fi
+if [ "$dependerrARRAY" ]; then echo -e " \e[1;31m\nerror$clre \e[0;31mFollowing dependencies not found at repositories:$clre ${dependerrARRAY[@]}"; rm .makedeps; exit 2; else [ -f .makedeps ] && { sudo apt install $(cat .makedeps | tr "\n" " ") ; printf " \e[0;32mok$clre" ; }; fi
 printf "\n\e[1;32mDownloading sources...$clre\n"
 for source_get in ${sources[@]}; do
 	source_get_mtd="$(echo $source_get | cut -d":" -f1)"
